# Indices

Indices is another word for powers. In this section we move beyond the idea that powers are just repeated multiplications. 

## Index notation

Being comfortable moving between different ways to write powers helps when rearranging algebra.

> | $x^0 = 1$ except when $x=0$ then it's undefined
> | $x^-n = \frac{1}{x^n}$
> | $x^{\frac{1}{n}} = \sqrt[n]x$

Here are some examples:

$$
2^{-3} = \frac{1}{2^3} = \frac{1}{8}
$$
More generally.
$$
x^{-3} = \frac{1}{x^3}
$$
Anything to the power of zero is $1$:
$$
\pi^0 = 1
$$
Remember good old $\pi$? From working stuff out about circles $\pi = 3.14159...$

We can write roots too:

$$
16^{\frac{1}{2}} = \sqrt{16} = \pm4
$$
**Pro tip** When taking square roots remember there are two possible solutions. Since in the above example $4 \times 4 = 16$ and  $-4 \times -4 = 16$. So either answer is just fine.

### But why?

Just like we did with negative numbers we can extend the idea of what a power means by following a pattern. Here's a pattern to justify $x^0 = 1$ and $x^{-n} = \frac{1}{x^n}$.

$$
\begin{aligned} 10^3 &= 10 \times 10 \times 10 & = 1000 \\
10^2 &= 10 \times 10 & = 100 \\
10^1 &= 10 & = 10 \\
10^0 &= 1 & = 1 \\
10^{-1} &= \frac{1}{10} & = 0.1 \\
10^{-2} &= \frac{1}{10 \times 10} & = 0.01 \\
10^{-3} &= \frac{1}{10 \times 10 \times 10} & = 0.001 
\end{aligned}
$$

I'll come back to the justification about square roots after the next section.

## Rules of indices

There is a neat set of rules we can use when combining numbers with indices:

> | $x^n \times x^m = x^{n+m}$
> | $x^n \div x^m = x^{n-m}$
> | $(x^n)^m = x^{n \times m}$

When you multiply terms you add the powers.

$$
\begin{aligned} 3x^4 \times 5x^6 &= 3 \times 5 \times x^4 \times x^5 \\
&= 15 \times x^{4+5} \\
&= 15x^9
\end{aligned}
$$

Lets put it all together with a complicated example:

To rewrite $\dfrac{\sqrt[4]{x^5x^3}}{\sqrt[3]{x} \sqrt[6]{x^3}}$ in the form $x^n$, we need to use the following rules:

1. $a^n a^m = a^{n+m}$;
2. $\sqrt[n]{a} = a^{1/n}$;
3. $\left(a^n\right)^m = a^{n \times m}$;
4. $\frac{a^n}{a^m} = a^{n-m}$.

We will simplify the numerator and denominator separately to make the steps clearer. Firstly, applying rule 1, then rule 2, and then rule 3 to the numerator:

$$
\begin{aligned} \dfrac{\sqrt[4]{x^5x^3}}{\sqrt[3]{x} \sqrt[6]{x^3}} &= \dfrac{\sqrt[4]{x^8}}{\sqrt[3]{x} \sqrt[6]{x^3}} \\
 &= \dfrac{(x^8)^{1/4}}{\sqrt[3]{x} \sqrt[6]{x^3}} \\
 &= \dfrac{x^2}{\sqrt[3]{x} \sqrt[6]{x^3}}
\end{aligned}
$$

To simplify the denominator, we want to apply rule 2, then rule 3, and then rule 1:

$$
\begin{aligned} \dfrac{x^2}{\sqrt[3]{x} \sqrt[6]{x^3}} &= \dfrac{x^2}{x^{1/3} (x^3)^{1/6}} \\
 &= \dfrac{x^2}{x^{1/3} x^{1/2}} \\
 &= \dfrac{x^2}{x^{5/6}}
\end{aligned}
$$

Remember that we'll need to get common denominators when adding the fractions at the end:
$$
\begin{aligned} \frac{1}{3} + \frac{1}{2} &= \frac{1\times2}{3\times2}  + \frac{1\times3}{2\times3} \\
&= \frac{2}{6}  + \frac{3}{6} \\
&= \frac{5}{6}
\end{aligned}
$$

Finally, applying rule 4 and simplifying, 

$$
\begin{aligned} \dfrac{x^2}{x^{5/6}} &=x^2 \times x^{-5/6} \\
 &= x^{2-5/6} \\
 &= x^{12/6-5/6} \\
 &= x^{7/6}
\end{aligned}
$$

Lots of work with fractions here! 

Now try these questions. Don't worry if it takes a while to just solve one!

```{r, echo=FALSE}
knitr::include_url("https://numbas.mathcentre.ac.uk/question/64712/indices-change-of-notation-3/embed/?token=246845ab-e1ea-4745-9106-5750be81ed2c", height="800px")
```

### But why? Square roots

As promised here is an explanation of why $x^{\frac{1}{n}} = \sqrt[n]x$.

When we take a square root we look for the a number that when it is multiplied by it's self we get the answer i.e. $? \times ? = x$. Since one $x$ is the same as $x^1$ we can rewrite out statement again:

$$
\begin{aligned} ? \times ? &= x^1 \\
x^? \times x^? &= x^1 \\
x^{?+?} &= x^1
\end{aligned}
$$
This means $? + ? = 1$ so $?=\frac{1}{2}$ so $x^{\frac{1}{2}} = \sqrt{x}$.
