project:
  output-dir: docs
  type: book

book:
  title: "zero-to-hero"
  author: "Ed Southwood"
# date removed from here and added to the index.qmd to enable using
# r code for automatic date
  search: true
  reader-mode: true
  repo-url: https://github.com/BathMASH/zero-to-hero
  repo-branch: master
  repo-actions: [source, issue]
  downloads: [pdf]
#  downloads: [pdf, docx, epub]
  chapters:
    - index.qmd
    - 01-negative_numbers.qmd
    - 02-algebraic_expressions.qmd
    - 03-expressions_with_brackets.qmd
    - 04-fractions.qmd
    - 05-solving_equations.qmd
    - 00-reading_mathematics.qmd
    - 06-straight_line_graphs.qmd
    - 07-quadratics.qmd
    - 08-indices.qmd
    - 09-differentiation.qmd
    - 10-exponetial_function.qmd
    - 11-logarithms.qmd
    - 12-further-differentiation.qmd
#    - 13-optimisation.qmd
  margin-footer: |
   [![](/img/cc-logo.png){fig-alt="Zero to Hero © 2023 by Ed Southwood, Skills Centre, University of Bath is licensed under Attribution-NonCommercial-ShareAlike 4.0 International"}](https://creativecommons.org/licenses/by-nc-sa/4.0/)

format:
  html:
    theme:
      light: cosmo
      dark: darkly
  pdf:
    documentclass: scrbook
    papersize: a4
    include-in-header:
      file: "preamble.tex"
#  docx:
#    toc: true
#    number-sections: true
#    highlight-style: github
#  epub:
#    toc: true
#    html-math-method: mathjax

knitr:
  opts_chunk:
    dev: 'png'

execute:
  cache: true
