project:
  output-dir: docs
  type: book

book:
  title: "zero-to-hero"
  author: "Ed Southwood"
# date removed from here and added to the index.qmd to enable using
# r code for automatic date
  search: true
  repo-url: https://github.com/BathMASH/zero-to-hero
  repo-actions: [source]
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - 01-negative_numbers.qmd
    - 02-algebraic_expressions.qmd
    - 03-expressions_with_brackets.qmd
    - 04-fractions.qmd
    - 05-solving_equations.qmd
    - 00-reading_mathematics.qmd
    - 06-straight_line_graphs.qmd
    - 07-quadratics.qmd
    - 08-indices.qmd
    - 09-differentiation.qmd
    - 10-exponetial_function.qmd
    - 11-logarithms.qmd
    - 12-further-differentiation.qmd
    - 13-optimisation.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
  pdf:
    documentclass: scrbook
    papersize: a4
    include-in-header:
      file: "preamble.tex"
  docx:
    toc: true
    number-sections: true
    highlight-style: github

knitr:
  opts_chunk:
    dev: 'png'

execute:
  cache: true
