book:
  chapters:
    - index.qmd                          # preface
    - 01-negative_numbers.qmd            # ch 1
    - 02-algebraic_expressions.qmd       # ch 2
    - 03-expressions_with_brackets.qmd   # ch 3
    - 04-fractions.qmd                   # ch 4
    - 05-solving_equations.qmd           # ch 5
    - 00-reading_mathematics.qmd         # ch 6
    - 06-straight_line_graphs.qmd        # ch 7
    - 07-quadratics.qmd                  # ch 8
    - 08-indices.qmd                     # ch 9
    - 09-differentiation.qmd             # ch 10
    - 10-exponetial_function.qmd         # ch 11
    - 11-logarithms.qmd                  # ch 12
    - 12-further-differentiation.qmd     # ch 13
    - 13-optimisation.qmd                # ch 14