project:
  output-dir: docs
  type: book

include-after-body:
  text: |
    <!-- Cloudflare Web Analytics --><script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "45c34618a8294826b85725434b26e3db"}'></script><!-- End Cloudflare Web Analytics -->
    <script type="application/javascript" src="scripts/light-dark.js"></script>

book:
  title: "Zero to Hero"
  author: "Ed Southwood"
# date removed from here and added to the index.qmd to enable using
# r code for automatic date
  search: true
  reader-mode: true
  repo-url: https://github.com/BathMASH/zero-to-hero
  repo-branch: master
  repo-actions: [source, issue]
  downloads: [pdf]
#  downloads: [pdf, docx, epub]

  margin-footer: |
   [![](/img/uob-logo.light.png){fig-alt="Zero to Hero © 2023 by Ed Southwood, Skills Centre, University of Bath is licensed under Attribution-NonCommercial-ShareAlike 4.0 International"}](https://creativecommons.org/licenses/by-nc-sa/4.0/)
   [![](/img/cc-logo.png){fig-alt="Zero to Hero © 2023 by Ed Southwood, Skills Centre, University of Bath is licensed under Attribution-NonCommercial-ShareAlike 4.0 International"}](https://creativecommons.org/licenses/by-nc-sa/4.0/)

format:
  html:
    theme:
      light: cosmo
      dark: darkly
  pdf:
    documentclass: scrbook
    papersize: a4
    include-in-header:
      file: "preamble.tex"
#  docx:
#    toc: true
#    number-sections: true
#    highlight-style: github
#  epub:
#    toc: true
#    html-math-method: mathjax

knitr:
  opts_chunk:
    dev: 'png'

#execute:
#  cache: true

profile:
  group: 
    - [all, apeb]
